services:
  db:
    container_name: mysql
    restart: unless-stopped
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: jocks-karaoke
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./data:/var/lib/mysql/
    networks:
      - host
      - jocks-karaoke
  pma:
    container_name: phpMyAdmin
    image: library/phpmyadmin:latest
    ports:
      - "8080:80"
    networks:
      - jocks-karaoke
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local