services:
  db:
    container_name: mysql
    restart: unless-stopped
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: jocks-karaoke
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./data:/var/lib/mysql/

  phpmyadmin:
    container_name: php-my-admin
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD

volumes:
  dbdata:
    driver: local